openapi: 3.0.0
info:
  title: API de para agregar una nueva ruta de vuelo
  version: 1.0.0
  description: API para gestionar rutas de vuelo en la aplicaci칩n web

paths:
  /create-route:
    post:
      summary: Crear una nueva ruta de vuelo
      description: Agrega una nueva ruta a la lista de rutas disponibles usando el campo proporcionado por el usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_route:
                  type: string
                  example: "NuevaRuta"
              required:
                - new_route
      responses:
        '201':
          description: Se cre칩 la nueva ruta correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: {'message': 'Ruta "{new_route}" creada correctamente'}
        '400':
          description: Par치metro `new_route` faltante o inv치lido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: {'message': 'Se requiere el nombre de la nueva ruta'}
        '500':
          description: Error interno al intentar agregar la ruta de vuelo a la lista de vuelos diponibles
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: {'message': 'Error al crear la nueva ruta'}
